### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Remski01** [DominicLuidold/SimpleBroadcast#18]
Can you make the plugin work with VanishNoPacket because if i have use the %online% tag they can see the vanish players and thats not what i want :(

So can you make this work with VanishNoPacket. that if they are in vanish that they not with the %online% tag

Sorry for my bad engels. Its not my best thing xD
Also sorry that i not post it by the Requiest thing i dont get how i make there an poll for this :(

**Comment by KingDome24** [comment]
Hello,

unfortunately VanishNoPacket doesn't provide an interface which I could use to implement this.
I'm sorry - you could ask the plugin developer of VNP if he maybe could add it.

Kind regards,
KingDome24

**Comment by DutchUser** [comment]
I make also an ticket by that plugin and this was his reaction,

VNP provides several ways in which another plugin can determine visibility.

Metadata set on the player. Check the 'vanished' metadata. If it exists, and asBoolean is true, they are invis, otherwise visible.
Various methods inside VNP are accessible, not advisable.
Events are fired, not as advisable.

**Comment by KingDome24** [comment]
Hello,

unfortunately this wasn't apparent from the BukkitDev website of VNP.
I'll have a look into it for v1.9.

Kind regards,
KingDome24

**Comment by DutchUser** [comment]
Thanks :)

**Comment by KingDome24** [comment]
Hello,

this feature got added and will be available in v1.9.

Kind regards,
KingDome24
